### ISSUE TITLE
install and setup issue

### ISSUE THREAD

**Issue by ccZhao-stu** [Xilinx/RapidWright#1033]
From the documentation [https://www.rapidwright.io/docs/RapidWright.pdf], I try to install the RapidWright use the 2.2 install; 
`git clone https://github.com/Xilinx/RapidWright.git
cd RapidWright
./gradlew compileJava
export PATH=`pwd`/bin:$PATH`
and then `rapidwright DeviceBrowser` try to check it.
But failed, please look this picture, thanks.
![Uploading d55268be-834f-422d-bcc9-e3dafced53b4.jpeg…]()

**Comment by ccZhao-stu** [comment]
`~/RapidWright-master]$ ./gradlew compileJava
Downloading https://services.gradle.org/distributioons/gradle-7.4.2-bin.zip
Exception in thread "main" java.net.UnknownHostExceptionservices.gradle.org
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractRlainSocketImpl.java:220)
at java.base/java.net.SocksSocketImpl.connect(SocksSockeetImpl.java:392)
at java.base/java.net.Socket.connect(Socket.java:609)
at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSSocketImpl.java:289)
at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
at java.base/sun.net.www.http.HttpClient.openServver(HttpClient.java:474)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
at java.base/sun.net.www.protocol.https.HttpsClient.<iniit>(HttpsClient.java:265)
at java.base/sun.net.www.protocol.https.Httpsclieent.New(HttpsClient.java:372)
at java.base/sun.net.www.protocol.https.AbstractDelegateeHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
at
java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsUfRLConnection.connect (AbstractDelegateHttpsURLConnection.java:189)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getinputstream0(HttpURLConnection.java:1592)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getinputStream(HttpURLConnection.java:15220)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionimpl.getInputStream(HttpsURLConnectionImpl.java:250)
at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
at org.gradle.wrapper.Download.download(Download.java:522)
at org.gradle.wrapper.Install$1.call(Install.java:62)
at org.gradle.wrapper.Install$1.call(Install.java:48)
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
at org.gradle.wrapper.Install.createDist(IInstall.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExeecutor.java:107)
at org.gradle.wrapper.GradleWrapperMain.main(GraadleWrapperMain.java:63
`
` [~/RapidWright-master]$ rapidwright DeviceBrowser
RapidWright not yet compiled. Please run './gradlew compilejava' from 'RapidWright-master
`
