### ISSUE TITLE
Unable to modify Versal (VCK190) DCP.

### ISSUE THREAD

**Issue by Arjun-Khanna** [Xilinx/RapidWright#1123]
I'm using the latest version of RapidWright (2024.2). However it is unable to generate the intersite_delay_terms.txt file for Versal. The error is as follows:
java.io.FileNotFoundException: C:\Users\arkhanna\RapidWright\timing\versal\intersite_delay_terms.txt (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at com.xilinx.rapidwright.timing.TimingModel.readDelayTerms(TimingModel.java:503)
	at com.xilinx.rapidwright.timing.TimingModel.build(TimingModel.java:243)
	at com.xilinx.rapidwright.FlopSiteTileMapping.main(FlopSiteTileMapping.java:28)

**Comment by clavin-xlnx** [comment]
Thank you for the feedback.  Unfortunately, we don't have timing model numbers for Versal yet in RapidWright.  We do have them for UltraScale+ devices.  We do have support in RWRoute (the RapidWright router) to route in Versal.  Let us know how we can best help with your application.

**Comment by clavin-xlnx** [comment]
Closing as this appears resolved.  Please re-open or file a new issue if there are additional concerns.
