### ISSUE TITLE
make multiple black boxes

### ISSUE THREAD

**Issue by pwang7** [Xilinx/RapidWright#966]
I'm following the tutorial [Reuse Timing-closed Logic As A Shell](https://www.rapidwright.io/docs/ReusingTimingClosedLogicAsAShell.html), and I'd like to make multiple black boxes in my DCP. I made a black box and generated the first shell DCP successfully using [MakeBlackbox](https://github.com/Xilinx/RapidWright/blob/60a571446d1bb78b9aba6ed497914631c2e7bc97/src/com/xilinx/rapidwright/util/MakeBlackBox.java#L35), but when I made another black box to the previous generated shell, I encountered the following error:
```
==============================================================================
==                               MakeBlackbox                               ==
==============================================================================
                Read DCP:     2.939s
Exception in thread "main" java.lang.RuntimeException: ERROR: Failed to add cell black_box0 to library work. The library already contains a cell with the same name.
        at com.xilinx.rapidwright.edif.EDIFLibrary.addCell(EDIFLibrary.java:76)
        at com.xilinx.rapidwright.edif.EDIFCell.<init>(EDIFCell.java:67)
        at com.xilinx.rapidwright.design.DesignTools.makeBlackBox(DesignTools.java:1851)
        at com.xilinx.rapidwright.design.DesignTools.makeBlackBox(DesignTools.java:1512)
        at com.xilinx.rapidwright.util.MakeBlackBox.main(MakeBlackBox.java:49)
```

I'm using [RapidWright 2023.2.0-beta Release](https://github.com/Xilinx/RapidWright/releases/tag/v2023.2.0-beta).

**Comment by pwang7** [comment]
After read the [MakeBlackbox](https://github.com/Xilinx/RapidWright/blob/60a571446d1bb78b9aba6ed497914631c2e7bc97/src/com/xilinx/rapidwright/util/MakeBlackBox.java#L35) source code, it does support cut multiple black boxes:
```
rapidwright MakeBlackBox <input.dcp> <output_shell.dcp> <blackbox cell 1> <blackbox cell 2> ...
```
